/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppComicComicIdRouteImport } from './routes/_app/comic.$comicId'
import { Route as AppExploreLatestRouteImport } from './routes/_app/explore_.latest'
import { Route as AppExploreRankingRouteImport } from './routes/_app/explore_.ranking'
import { Route as AppExploreSearchRouteImport } from './routes/_app/explore_.search'
import { Route as ReaderComicIdChapterIdRouteImport } from './routes/reader.$comicId.$chapterId'
import { Route as AppExploreCategoryCategoryIdRouteImport } from './routes/_app/explore_.category.$categoryId'
import { Route as AppExploreCreatorKindCreatorIdRouteImport } from './routes/_app/explore_.creator.$kind.$creatorId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppComicComicIdRoute = AppComicComicIdRouteImport.update({
  id: '/comic/$comicId',
  path: '/comic/$comicId',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreLatestRoute = AppExploreLatestRouteImport.update({
  id: '/explore_/latest',
  path: '/explore/latest',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRankingRoute = AppExploreRankingRouteImport.update({
  id: '/explore_/ranking',
  path: '/explore/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreSearchRoute = AppExploreSearchRouteImport.update({
  id: '/explore_/search',
  path: '/explore/search',
  getParentRoute: () => AppRoute,
} as any)
const ReaderComicIdChapterIdRoute = ReaderComicIdChapterIdRouteImport.update({
  id: '/reader/$comicId/$chapterId',
  path: '/reader/$comicId/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExploreCategoryCategoryIdRoute =
  AppExploreCategoryCategoryIdRouteImport.update({
    id: '/explore_/category/$categoryId',
    path: '/explore/category/$categoryId',
    getParentRoute: () => AppRoute,
  } as any)
const AppExploreCreatorKindCreatorIdRoute =
  AppExploreCreatorKindCreatorIdRouteImport.update({
    id: '/explore_/creator/$kind/$creatorId',
    path: '/explore/creator/$kind/$creatorId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/explore': typeof AppExploreRoute
  '/favorites': typeof AppFavoritesRoute
  '/history': typeof AppHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/comic/$comicId': typeof AppComicComicIdRoute
  '/explore/latest': typeof AppExploreLatestRoute
  '/explore/ranking': typeof AppExploreRankingRoute
  '/explore/search': typeof AppExploreSearchRoute
  '/reader/$comicId/$chapterId': typeof ReaderComicIdChapterIdRoute
  '/explore/category/$categoryId': typeof AppExploreCategoryCategoryIdRoute
  '/explore/creator/$kind/$creatorId': typeof AppExploreCreatorKindCreatorIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/explore': typeof AppExploreRoute
  '/favorites': typeof AppFavoritesRoute
  '/history': typeof AppHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/comic/$comicId': typeof AppComicComicIdRoute
  '/explore/latest': typeof AppExploreLatestRoute
  '/explore/ranking': typeof AppExploreRankingRoute
  '/explore/search': typeof AppExploreSearchRoute
  '/reader/$comicId/$chapterId': typeof ReaderComicIdChapterIdRoute
  '/explore/category/$categoryId': typeof AppExploreCategoryCategoryIdRoute
  '/explore/creator/$kind/$creatorId': typeof AppExploreCreatorKindCreatorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/comic/$comicId': typeof AppComicComicIdRoute
  '/_app/explore_/latest': typeof AppExploreLatestRoute
  '/_app/explore_/ranking': typeof AppExploreRankingRoute
  '/_app/explore_/search': typeof AppExploreSearchRoute
  '/reader/$comicId/$chapterId': typeof ReaderComicIdChapterIdRoute
  '/_app/explore_/category/$categoryId': typeof AppExploreCategoryCategoryIdRoute
  '/_app/explore_/creator/$kind/$creatorId': typeof AppExploreCreatorKindCreatorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/explore'
    | '/favorites'
    | '/history'
    | '/settings'
    | '/comic/$comicId'
    | '/explore/latest'
    | '/explore/ranking'
    | '/explore/search'
    | '/reader/$comicId/$chapterId'
    | '/explore/category/$categoryId'
    | '/explore/creator/$kind/$creatorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/explore'
    | '/favorites'
    | '/history'
    | '/settings'
    | '/'
    | '/comic/$comicId'
    | '/explore/latest'
    | '/explore/ranking'
    | '/explore/search'
    | '/reader/$comicId/$chapterId'
    | '/explore/category/$categoryId'
    | '/explore/creator/$kind/$creatorId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/explore'
    | '/_app/favorites'
    | '/_app/history'
    | '/_app/settings'
    | '/_app/'
    | '/_app/comic/$comicId'
    | '/_app/explore_/latest'
    | '/_app/explore_/ranking'
    | '/_app/explore_/search'
    | '/reader/$comicId/$chapterId'
    | '/_app/explore_/category/$categoryId'
    | '/_app/explore_/creator/$kind/$creatorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReaderComicIdChapterIdRoute: typeof ReaderComicIdChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comic/$comicId': {
      id: '/_app/comic/$comicId'
      path: '/comic/$comicId'
      fullPath: '/comic/$comicId'
      preLoaderRoute: typeof AppComicComicIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore_/latest': {
      id: '/_app/explore_/latest'
      path: '/explore/latest'
      fullPath: '/explore/latest'
      preLoaderRoute: typeof AppExploreLatestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore_/ranking': {
      id: '/_app/explore_/ranking'
      path: '/explore/ranking'
      fullPath: '/explore/ranking'
      preLoaderRoute: typeof AppExploreRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore_/search': {
      id: '/_app/explore_/search'
      path: '/explore/search'
      fullPath: '/explore/search'
      preLoaderRoute: typeof AppExploreSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/reader/$comicId/$chapterId': {
      id: '/reader/$comicId/$chapterId'
      path: '/reader/$comicId/$chapterId'
      fullPath: '/reader/$comicId/$chapterId'
      preLoaderRoute: typeof ReaderComicIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/explore_/category/$categoryId': {
      id: '/_app/explore_/category/$categoryId'
      path: '/explore/category/$categoryId'
      fullPath: '/explore/category/$categoryId'
      preLoaderRoute: typeof AppExploreCategoryCategoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore_/creator/$kind/$creatorId': {
      id: '/_app/explore_/creator/$kind/$creatorId'
      path: '/explore/creator/$kind/$creatorId'
      fullPath: '/explore/creator/$kind/$creatorId'
      preLoaderRoute: typeof AppExploreCreatorKindCreatorIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComicComicIdRoute: typeof AppComicComicIdRoute
  AppExploreLatestRoute: typeof AppExploreLatestRoute
  AppExploreRankingRoute: typeof AppExploreRankingRoute
  AppExploreSearchRoute: typeof AppExploreSearchRoute
  AppExploreCategoryCategoryIdRoute: typeof AppExploreCategoryCategoryIdRoute
  AppExploreCreatorKindCreatorIdRoute: typeof AppExploreCreatorKindCreatorIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppComicComicIdRoute: AppComicComicIdRoute,
  AppExploreLatestRoute: AppExploreLatestRoute,
  AppExploreRankingRoute: AppExploreRankingRoute,
  AppExploreSearchRoute: AppExploreSearchRoute,
  AppExploreCategoryCategoryIdRoute: AppExploreCategoryCategoryIdRoute,
  AppExploreCreatorKindCreatorIdRoute: AppExploreCreatorKindCreatorIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ReaderComicIdChapterIdRoute: ReaderComicIdChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
